### ISSUE TITLE
As User i want to see information, that already exists on OSM map within MAPA and from MAPA to OSM too.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#12]

**Comment by wellemut** [comment]
We have discussed this issue since the beginning, because this connection seems to be so obvious
You can test the osm layer on the mobile version: https://m.kartevonmorgen.org/mobile.html#;49.400686950065214,8.428745269775392
Here is the expericence https://github.com/goodmap/goodmap-old/issues/13
Performance issues: https://github.com/goodmap/goodmap-old/issues/413

**Comment by rizomaa** [comment]
@wellemut do you mean mobile and laptop versions are different?
